name: Run Telegraf in GitHub Actions

on: 
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  run-telegraf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Telegraf
        run: |
          sudo apt update
          sudo apt install -y telegraf

      - name: Configure Telegraf
        run: |
          echo '[[inputs.mqtt_consumer]]' > telegraf.conf
          echo 'servers = ["ssl://broker.emqx.io:8883"]' >> telegraf.conf
          echo 'topics = ["farm/sensor"]' >> telegraf.conf
          echo 'data_format = "json"' >> telegraf.conf
          echo '[[outputs.influxdb_v2]]' >> telegraf.conf
          echo 'urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]' >> telegraf.conf
          echo 'token = "${{ secrets.INFLUXDB_TOKEN }}"' >> telegraf.conf
          echo 'organization = "YOUR_ORG_NAME"' >> telegraf.conf
          echo 'bucket = "farmflow"' >> telegraf.conf

      - name: Run Telegraf
        run: telegraf --config telegraf.conf

