name: Run Telegraf in GitHub Actions

on: 
  push:
    branches:
      - main  # Runs when you push to main branch

jobs:
  run-telegraf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Telegraf
        run: |
          sudo apt update
          sudo apt install -y telegraf

      - name: Configure Telegraf
        run: |
          echo '[[inputs.mqtt_consumer]]' > telegraf.conf
          echo 'servers = ["ssl://ca6f126b.ala.asia-southeast1.emqxsl.com:8883"]' >> telegraf.conf
          echo 'topics = ["farmflow/test"]' >> telegraf.conf
          echo 'username = "admin"' >> telegraf.conf
          echo 'password = "admin11223"' >> telegraf.conf
          echo 'data_format = "json"' >> telegraf.conf
          echo '[[outputs.influxdb_v2]]' >> telegraf.conf
          echo 'urls = ["https://us-east-1-1.aws.cloud2.influxdata.com"]' >> telegraf.conf
          echo 'token = "${{ secrets.INFLUXDB_TOKEN }}"' >> telegraf.conf
          echo 'organization = "FarmFlow"' >> telegraf.conf
          echo 'bucket = "FarmFlow"' >> telegraf.conf

      - name: Run Telegraf
        run: telegraf --config telegraf.conf
